#!/usr/bin/env bash
# Server -01 login commands for the this task

# Setting up the SSH-agent 
eval $("ssh-agent")

# Path to identityFile
ssh-add ~/.ssh/school

#username and IP Address
ssh ubuntu@18.209.224.197

