#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive  of it
# This script is actually for the backing up purposes
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
